# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: '$(KEYSTOREFILE)'
    retryCount: '3'
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'assembleRelease'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false
- script: |
    sudo cp -r app/build/bakApk $(Build.ArtifactStagingDirectory)
    sudo cp app/release/* $(Build.ArtifactStagingDirectory)
    sudo cp app/build/outputs/mapping/release/mapping.txt $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Class Schedule'
    publishLocation: 'Container'